### ISSUE TITLE
The problem I have!

### ISSUE THREAD

**Issue by cymilad** [nwqda/BiG-Brother#1]
![wwwwwwwww](https://user-images.githubusercontent.com/22496001/138647178-e87c4b1e-bee4-4626-8f29-ba0bfa72925a.PNG)

[🤖] What type of camera are you looking for?  All
[🏳️] In which country do you want to focus your research?  US
[/] The research of cameras has begun. It may take a while, please be patient.

[🚫] Error: Retry limit reached (5). Please, try again.
[😓] No result found. Please try again using another keywords or dorks combo.

[👹] See you soon for a new adventure!

**Comment by nwqda** [comment]
Hi @cymilad,

You've got this error because you are using a free Shodan account which limits you to only 5 requests/day to their server.
